# parameters for tweaking the poses of each of the goals + tolerances

scoring:
  ros__parameters:
    tolerances: # in meters / radians
      x:
      y:
      th:
    long_goals:
      q1_q3:

    loaders:


